######################################
##     Reusable Codecov Workflow    ##
######################################

on:
  workflow_call:
    inputs:
      coverage_artifact:
        required: true
        type: string
        description: "Name of the coverage artifact to upload to Codecov"
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  upload_coverage:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Download the coverage artifact
      - name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage_artifact }}

      # Get the Codecov binary
      - name: Get Codecov Binary
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov

      # DOWNLOAD XML FILES FROM ARTIFACTS
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage
          pattern: coverage-*
          merge-multiple: true

      - run: ls -R coverage

      # Upload coverage reports to Codecov
      - name: Upload Coverage Reports to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # this is "read" from inputs
        run: |
          for file in coverage*.xml; do
            OS_NAME=$(echo $file | sed -E "s/coverage-(\w+)-.*/\1/")
            PY_VERSION=$(echo $file | sed -E "s/coverage-\w+-(\d+\.\d+).*/\1/")
            echo "---> [INFO] Sending: $file"
            ./codecov -f $file -e "OS=$OS_NAME,PYTHON=$PY_VERSION" --flags unittests --verbose
          done
